export type Climate = 'HEAVY_RAIN_OR_FLOOD' | 'TEMPERATURE_RISE' | 'TYPHOON_OR_TORNADO' | 'FINE_DUST' | 'DROUGHT_OR_DESERTIFICATION' | 'SEA_LEVEL_RISE' | 'WILDFIRE' | 'EARTHQUAKE' | 'DEFORESTATION' | 'BIODIVERSITY_LOSS'

